### ISSUE TITLE
Encontre una mejora al termino de guardar o registrar producto

### ISSUE THREAD

**Issue by Juancruzd** [LGsusMx/OurClothes#9]
![image](https://user-images.githubusercontent.com/42796029/99605389-33431180-29cd-11eb-84a8-27e9ae12a52a.png)
Al termino de la subida o registro se esconde o se oculta el modal.
@LGsusMx  @duarteissc  @Kevin-Maniakevin

**Comment by LGsusMx** [comment]
Muy buena observación @Juancruzd , realiza un push hacia la rama correspondiente 👍
